export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CONFIRM = 'AUTH_CONFIRM';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';


export const UPDATE_BASIC = 'UPDATE_BASIC';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_CREDIT = 'UPDATE_CREDIT';


export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";

export const UPDATE_TYPE = "UPDATE_TYPE";
export const UPDATE_NUM = "UPDATE_NUM";
export const UPDATE_UNIT = "UPDATE_UNIT";


export const ADD_DIRECTION = "ADD_DIRECTION";
export const DELETE_DIRERCTION = "DELETE_DIRERCTION";
export const UPDATE_DIRECTION = "UPDATE_DIRECTION";

export const UPLOAD_RECIPE = "UPLOAD_RECIPE";