version: 2
machine:
  environment:
    DEPLOY_DIR: $HOME
    
    AWS_CODE_DEPLOY_REGION: us-east-1
    AWS_CODE_DEPLOY_APPLICATION_NAME: "Columbia-fresh"
    AWS_CODE_DEPLOY_DEPLOYMENT_CONFIG_NAME: CodeDeployDefault.AllAtOnce
    AWS_CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: "columbiaFresh"
    AWS_CODE_DEPLOY_APP_SOURCE: $HOME
    AWS_CODE_DEPLOY_S3_FILENAME: "${CIRCLE_BUILD_NUM}#${CIRCLE_SHA1:0:7}.zip"
    AWS_CODE_DEPLOY_S3_BUCKET: Columbia-fresh
    AWS_CODE_DEPLOY_DEPLOYMENT_DESCRIPTION: "Deployed via CircleCI on $(date)"

jobs:
  deployment:
    production:
      branch: development
      commands:
        - bash bin/aws-code-deploy.sh
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/mysql:5.7.19

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            echo "The first test!"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      #- run:
      #    name: run tests
      #    command: |
      #      . venv/bin/activate
      #      python manage.py test

      #- store_artifacts:
      #    path: test-reports
      #    destination: test-reports
